root_path: images/
background_folder: cars/
foreground_objects:
  #Typlabel-China: ISI-Typlabelchina-Schilder/
  #Typlabel-USA: ISI-Typlabelchina-Schilder/
  Typlabel-Japan: ISI-Typlabelchina-Schilder/
annotation: PascalVOC
size: [2304, 1728]