transformations:
  "Klimaschild-China":
    - "name": "AffineTransformationFromDataFrame"
      "dataframe_path": "standard"
    - "name": "ScaleToAreaFromDataFrame"
      "dataframe_path": "standard"
      "background_size": 3981312

#    - "name": "Greyscale"
#    - "name": "ShearYFromDataFrame"
#      "dataframe_path": "standard"
#    - "name": "RotateFromDataFrame"
#      "dataframe_path": "standard"
#    - "name": "ShearXFromDataFrame"
#      "dataframe_path": "standard"
#    - "name": "ScaleToAreaFromDataFrame"
#      "dataframe_path": "standard"
#      "background_size": 3981312
#  "Background":
#    - "name": "Zoom"
#      "zoom_factor": 1
#      "zoom_position_x": 0.5
#      "zoom_position_y": 0.8

filters:
  - "name": "TargetBrightnessFromDataFrame"
    "dataframe_path": "standard"
    "class_name": "Klimaschild-China"

blending: "Standard"

positioning: 
  "name": "DataframePositionDeterminer"
  "dataframe_path": "standard"

total_images: 1000
seed: 42
object_amount: 
  "Klimaschild-China": 1
