transformations:
  "Typlabel-Japan":
    - "name": "Rotate"
      "angle": 45
    - "name": "Scale"
      "factor": 0.4
    #- "name": "ShearY"
    #  "shear_factor": 0.5
  "Background":
    - "name": "Zoom"
      "zoom_factor": 1.5

filters:
  - "name": "Brightness"
    "brightness_factor": 1.2

blending: "Standard"

positioning: 
  "name": "RandomPositionNoCollisionDeterminer"
  "bounds": [0, 1, 0, 1]
  "max_attempts": 1000

total_images: 20
seed: 42
object_amount: 
  "Typlabel-Japan":
    "max": 3
    "prob": 1.0
