transformations:
  "Klimaschild-Japan":
    - "name": "HomographyTransformationFromDataFrame"
      "dataframe_path": "standard"
    - "name": "ScaleToAreaFromDataFrame"
      "dataframe_path": "standard"
      "background_size": 1127000
filters:
  - "name": "TargetBrightnessFromDataFrame"
    "dataframe_path": "standard"
    "class_name": "Klimaschild-Japan"

blending: "Standard"

positioning: 
  "name": "DataframePositionDeterminer"
  "dataframe_path": "standard"

total_images: 10
seed: 42
object_amount: 
  "Klimaschild-Japan": 1
